### ISSUE TITLE
Ошибка правила: TypeError: call target not an object

### ISSUE THREAD

**Issue by lin4in** [4mr/wb-mqtt-homeassistant#2]
Привет! Что-то не заводится интеграция. Делал согласно инструкции.
Добавил файл: /etc/wb-rules-modules/hass.js
Добавил конфиг в правила на WB через web-интерфейс в новый файл HA_integration.js:

```
var config = {
  topic: 'homeassistant',
  ignore: ['Serial'],
  devices: [
    {name: 'wb-mdm3_133'},
  ]
};

var hass = require("hass");
hass.init(config); --- явно выделяется данная строка.
```

```
Ошибка правила: TypeError: call target not an object
duk_js_executor.c:2761
anon /etc/wb-rules/HA_integration.js:10 preventsyield
```
При включенном дебаге RULES ничего нового в messages не пишется.
WB - 2022.07

Готов что-то оперативно тестировать и предоставить детальную информацию.

**Comment by 4mr** [comment]
Проверьте что файл /etc/wb-rules-modules/hass.js правильный и нужного размера, почему то иногда github отдает 0 байт.

**Comment by 4mr** [comment]
Попробуйте новый проект: https://github.com/4mr/wb-engine

**Comment by lin4in** [comment]
Спасибо, не проверил скачанный файл hass.js. Был нулевого размера.
Перешел на новый проект. Попробую загнать все свои устройства. По результатам отпишусь.
